apiVersion: 1

deleteDatasources:
  - name: InfluxDB_Flux
    orgId: 1

datasources:
  - name: InfluxDB_Flux
    uid: InfluxDB_Flux
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: cdd-org
      defaultBucket: cdd-bucket
    secureJsonData:
      token: cdd-super-secret-token
    editable: true
